# Generated by Django 5.2.9 on 2026-03-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desccription',
            new_name='description',
        ),
    ]
